name: Update Notification

on:
  push:
    branches:
      - master

jobs:
  notify_update:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Checkout the code
        uses: actions/checkout@v3.5.3

      - name: Check for GH_TOKEN and DISCORD_WEBHOOK_URL
        id: check_secrets
        run: |
          if [[ -z "${{ secrets.GH_TOKEN }}" || -z "${{ secrets.DISCORD_WEBHOOK_URL }}" ]]; then
            echo "Secrets GH_TOKEN or DISCORD_WEBHOOK_URL not provided. Skipping tasks."
            exit 1
          else
            echo "Secrets found. Proceeding with tasks."
            echo "result=success" >> $GITHUB_ENV
          fi

      - name: Fetch the latest commit details
        id: latest_commit
        if: env.check_secrets_result == 'success'
        run: |
          COMMIT_API_RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/VermeilChan/MetalSlugFont/commits?per_page=1")
          COMMIT_MESSAGE=$(echo "$COMMIT_API_RESPONSE" | jq -r '.[0].commit.message')
          COMMIT_SHA=$(echo "$COMMIT_API_RESPONSE" | jq -r '.[0].sha')
          COMMIT_URL=$(echo "$COMMIT_API_RESPONSE" | jq -r '.[0].html_url')
          SHORT_COMMIT_SHA=$(echo "$COMMIT_SHA" | cut -c 1-7)
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "commit_url=$COMMIT_URL" >> $GITHUB_ENV
          echo "short_commit_sha=$SHORT_COMMIT_SHA" >> $GITHUB_ENV

      - name: Send an embed message to Discord
        if: env.check_secrets_result == 'success'
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)
          LONG_DATE=$(date -u +"%A, %B %-d, %Y at %T")
          COMMIT_MESSAGE="${{ env.commit_message }}"
          COMMIT_URL="${{ env.commit_url }}"
          SHORT_COMMIT_SHA="${{ env.short_commit_sha }}"
          curl -X POST -H "Content-Type: application/json" -d '{
            "embeds": [
              {
                "title": "MetalSlugFont Update",
                "description": "MetalSlugFont has been updated with the following changes:",
                "color": 3447003,
                "thumbnail": {
                  "url": "https://cdn.discordapp.com/attachments/905835784215592960/1136337834689712138/sv-001.png"
                },
                "fields": [
                  {
                    "name": "Latest Commit",
                    "value": "**'"$COMMIT_MESSAGE"'**"
                  },
                  {
                    "name": "Commit ID",
                    "value": "[View Commit ('"$SHORT_COMMIT_SHA"')]('"$COMMIT_URL"')\n_Click the hyperlink to learn more about the changes._"
                  }
                ],
                "footer": {
                  "text": "Updated: '"$LONG_DATE"'"
                }
              }
            ]
          }' "${{ secrets.DISCORD_WEBHOOK_URL }}"
