name: Build MSFONT

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    - name: Cache Python dependencies
      uses: actions/cache@v3.3.2
      with:
        path: ~/.pip-cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PyInstaller
      uses: actions/cache@v3.3.2
      with:
        path: ~/.pyinstaller-cache
        key: ${{ runner.os }}-pyinstaller-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pyinstaller-

    - name: Update Pip
      run: |
        python -m pip install --upgrade pip
      shell: cmd

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.5

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build MSFONT
      run: pyinstaller --noconfirm --onedir --console --icon "Assets\ICON\Sv-001.ico" --name "MSFONT" --add-data "main.py;." --add-data "Assets;Assets/" "terminal.py"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT
        path: dist/MSFONT
