name: Build and Upload Executable

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile main.py

    - name: Create artifacts folder
      run: |
        mkdir artifacts
        mv dist/main.exe artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: executable-artifact
        path: artifacts/

    - name: Check artifact size
      run: |
        artifact_size=$(du -h artifacts/ | cut -f1)
        echo "Artifact size: $artifact_size"

    - name: Error handling and checks
      run: |
        if [ ! -f artifacts/main.exe ]; then
          echo "Error: Executable not found in artifacts folder."
          exit 1
        fi

        if [[ $artifact_size == *"M"* && $(echo $artifact_size | cut -d'M' -f1) -gt 10 ]]; then
          echo "Warning: Artifact size exceeds 10 MB."
        fi
