name: Build and Upload Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.4

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Run shell script
      run: |
        ./build_exe.sh

    - name: Create artifacts folder
      run: |
        mkdir artifacts
        mv dist/MetalSlugFont/MetalSlugFont.exe artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: executable-artifact
        path: artifacts/
