# Define the name of the workflow
name: Build and Upload MSFONT

# Trigger the workflow when code is pushed to the 'experimental' branch
on:
  push:
    branches:
      - experimental

# Define the jobs that will be executed as part of the workflow
jobs:
  build:
    # Specify the runner environment as Windows
    runs-on: windows-latest

    # Define the steps to be executed within the job
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    # Step 2: Update Python's pip package manager
    - name: Update Pip
      run: |
        python -m pip install --upgrade pip
      shell: cmd

    # Step 3: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11.5
        architecture: x64

    # Step 4: Install PyInstaller using pip
    - name: Install PyInstaller
      run: pip install pyinstaller

    # Step 5: Build the MSFONT application
    - name: Build MSFONT
      run: |
        pyinstaller --noconfirm --onedir --console --icon "${{ env.ASSET_ICON_PATH }}" --name "MSFONT" --add-data "main.py;." --add-data "Assets;Assets/" "terminal.py"
      env:
        ASSET_ICON_PATH: Assets/ICON/Sv-001.ico

    # Step 6: Upload artifacts (output files) to the workflow
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT  # Specify the name of the artifact
        path: dist/MSFONT  # Specify the path to the artifact files
