name: Build Python Application

on:
  push:
    branches:
      - experimental
  pull_request:
    branches:
      - experimental

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3

      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pip
          key: ubuntu-pip-3.10-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ubuntu-pip-3-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile main.py
          pyinstaller --onefile terminal.py
          mkdir dist/MSFONT
          cp -r Assets/* dist/MSFONT/
          cp Assets/ICON/Sv-001.ico dist/

      - name: Archive artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: app-artifacts
          path: dist/
