name: Build MSFONT

on:
  push:
    branches:
      - experimental

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.11.5, 3.10.11, 3.9.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    - name: Cache pip packages
      uses: actions/cache@v3.3.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Update Pip
      run: |
        python -m pip install --upgrade pip
      shell: cmd

    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build MSFONT
      run: |
        pyinstaller --noconfirm --onedir --console --icon "${{ env.ICON_PATH }}" --name "MSFONT" --add-data "${{ env.MAIN_PY }};." --add-data "${{ env.ASSETS_PATH }};Assets/" "${{ env.TERMINAL_PY }}"
      env:
        ASSETS_PATH: Assets
        ICON_PATH: Assets/ICON/Sv-001.ico
        MAIN.PY: main.py
        TERMINAL.PY: terminal.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: MSFONT
        path: dist/MSFONT
